import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'dictation_trace.dart';

/// Vocabulary mined from this machine's Claude Code transcripts.
///
/// The recogniser is tuned for general English and mangles project nouns —
/// "Convex" becomes "convicts", "e2e" becomes "eat to eat". [terms] biases it
/// back; [phrases] trains an on-device custom language model; [persona]
/// describes the user's prompt style for any downstream cleanup pass.
///
/// Generated by `scripts/mine_dictation_vocabulary.py`. Absent on a fresh
/// clone, in which case dictation still works — just untuned.
@immutable
class DictationVocabulary {
  const DictationVocabulary({
    required this.terms,
    required this.phrases,
    required this.persona,
  });

  static const empty = DictationVocabulary(terms: [], phrases: [], persona: {});

  final List<String> terms;
  final List<String> phrases;
  final Map<String, Object?> persona;

  bool get isEmpty => terms.isEmpty && phrases.isEmpty;

  /// Identifies this phrase set so the native side retrains the language model
  /// only when the vocabulary actually changed. Re-mining with no new prompts
  /// yields the same version and reuses the cached model.
  String get version {
    if (phrases.isEmpty) return 'empty';
    return Object.hashAll(phrases).toUnsigned(32).toRadixString(16);
  }

  static DictationVocabulary parse(String source) {
    final decoded = jsonDecode(source);
    if (decoded is! Map) return empty;
    List<String> strings(Object? raw) => raw is List
        ? raw.whereType<String>().where((s) => s.trim().isNotEmpty).toList()
        : const [];
    return DictationVocabulary(
      terms: strings(decoded['terms']),
      phrases: strings(decoded['phrases']),
      persona: decoded['persona'] is Map
          ? Map<String, Object?>.from(decoded['persona'] as Map)
          : const {},
    );
  }
}

/// What the recogniser is doing right now.
enum DictationState { idle, listening, unavailable }

/// A transcript update.
///
/// [isFinal] means "bank this" - the recogniser has committed these words and
/// will never revise them. It does *not* mean the session ended: iOS rotates
/// recognition tasks roughly every minute, and each rotation banks a segment
/// while dictation carries on. The stream closing is what ends a session.
@immutable
class DictationResult {
  const DictationResult({required this.text, required this.isFinal});

  final String text;
  final bool isFinal;
}

/// Why dictation could not start. Surfaced so the UI can route the user to
/// Settings rather than showing a dead button.
enum DictationError { speechDenied, microphoneDenied, unavailable, failed }

/// On-device dictation, backed by `ios/Runner/Dictation.swift`.
///
/// Same Apple engine as the keyboard's mic key, but biased toward this user's
/// vocabulary. Audio never leaves the device.
class DictationService {
  DictationService({AssetBundle? bundle, DictationTrace? trace})
      : _bundle = bundle ?? rootBundle,
        trace = trace ?? DictationTrace(send: (_) async {});

  /// Diagnostics sink. Off unless enabled from Settings.
  final DictationTrace trace;

  static const _methods = MethodChannel('medslides/dictation');
  static const _events = EventChannel('medslides/dictation/events');
  static const _asset = 'assets/dictation_vocabulary.json';

  final AssetBundle _bundle;

  DictationVocabulary _vocabulary = DictationVocabulary.empty;
  DictationVocabulary get vocabulary => _vocabulary;

  bool _prepared = false;
  StreamSubscription<dynamic>? _subscription;

  /// True where the native channel exists at all.
  bool get isSupported => !kIsWeb && Platform.isIOS;

  /// Load the mined vocabulary and train the custom language model.
  ///
  /// Safe to call repeatedly; the work happens once. Training takes a few
  /// seconds on first run for a given vocabulary version and is then cached on
  /// disk by the native side, so this is called ahead of the first tap rather
  /// than during it.
  Future<void> prepare() async {
    if (_prepared || !isSupported) return;
    _prepared = true;

    try {
      _vocabulary = DictationVocabulary.parse(await _bundle.loadString(_asset));
    } on FlutterError {
      // No mined vocabulary on this machine — dictate untuned.
      _vocabulary = DictationVocabulary.empty;
      return;
    } catch (error) {
      debugPrint('[dictation] vocabulary unreadable: $error');
      _vocabulary = DictationVocabulary.empty;
      return;
    }

    if (_vocabulary.phrases.isEmpty) return;
    try {
      await _methods.invokeMethod<bool>('prepare', {
        'phrases': _vocabulary.phrases,
        'version': _vocabulary.version,
      });
    } catch (error) {
      // The custom model is an enhancement; contextual strings still apply.
      debugPrint('[dictation] language model unavailable: $error');
    }
  }

  /// Request both grants dictation needs: speech recognition and the mic.
  Future<DictationError?> authorize() async {
    if (!isSupported) return DictationError.unavailable;
    try {
      final status = await _methods.invokeMethod<String>('authorize');
      switch (status) {
        case 'granted':
          return null;
        case 'speech_denied':
          return DictationError.speechDenied;
        case 'microphone_denied':
          return DictationError.microphoneDenied;
        default:
          return DictationError.failed;
      }
    } catch (error) {
      debugPrint('[dictation] authorize failed: $error');
      return DictationError.failed;
    }
  }

  /// Begin listening. Emits partial transcripts as the user speaks, then one
  /// final result. The stream closes when recognition ends.
  Stream<DictationResult> start() {
    final controller = StreamController<DictationResult>();

    Future<void> begin() async {
      await prepare();
      final denied = await authorize();
      if (denied != null) {
        controller.addError(denied);
        await controller.close();
        return;
      }

      _subscription = _events.receiveBroadcastStream().listen(
        (event) {
          if (event is! Map) return;
          final payload = Map<Object?, Object?>.from(event);
          final type = payload['type'];
          if (type == 'trace') {
            // Native diagnostics ride the same channel as transcripts.
            trace.add(
              payload['event'] as String? ?? 'native.?',
              gen: payload['gen'] as int?,
              textLen: payload['textLen'] as int?,
              note: payload['note'] as String?,
            );
            return;
          }
          if (type == 'error') {
            controller.addError(DictationError.failed);
            unawaited(controller.close());
            return;
          }
          final text = payload['text'];
          if (text is! String) return;
          switch (type) {
            case 'partial':
              controller.add(DictationResult(text: text, isFinal: false));
            case 'segment':
              // A task rotated. Bank the words; the session continues.
              controller.add(DictationResult(text: text, isFinal: true));
            case 'final':
              if (text.isNotEmpty) {
                controller.add(DictationResult(text: text, isFinal: true));
              }
              unawaited(controller.close());
          }
        },
        onError: (Object error) {
          controller.addError(DictationError.failed);
          unawaited(controller.close());
        },
      );

      try {
        await _methods.invokeMethod<void>('start', {
          'contextualStrings': _vocabulary.terms,
          'onDevice': true,
          'punctuation': true,
        });
      } catch (error) {
        debugPrint('[dictation] start failed: $error');
        controller.addError(DictationError.failed);
        await controller.close();
      }
    }

    controller.onCancel = () async {
      await _subscription?.cancel();
      _subscription = null;
    };
    unawaited(begin());
    return controller.stream;
  }

  /// Stop listening and let the recogniser flush a final transcript.
  Future<void> stop() async {
    trace.add('dart.stop');
    if (!isSupported) return;
    try {
      await _methods.invokeMethod<void>('stop');
    } catch (error) {
      debugPrint('[dictation] stop failed: $error');
    }
  }

  /// Abandon the utterance; no final transcript is emitted.
  Future<void> cancel() async {
    await _subscription?.cancel();
    _subscription = null;
    if (!isSupported) return;
    try {
      await _methods.invokeMethod<void>('cancel');
    } catch (error) {
      debugPrint('[dictation] cancel failed: $error');
    }
  }
}
